name: html_conversion

on:
  push:
    branches:
    - master
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor -D docs --backend=html5 -o index.html -a toc2 ddocs/index.adoc 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor '*.adoc' '*/*.adoc'"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./
    - name : Checkout gh-pages
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'gh-pages'
        persist-credentials: false
    - run: | 
        git remote add publication https://github.com/fabref-34/sismage-apollo-api-guidelines.git
        git config --global user.email "florian.fabre@total.com"
        git config --global user.name "f-fabre"
        git checkout gh-pages
        git push -u https://$REPO_KEY:x-oauth-basic@github.com/fabref-34/sismage-apollo-api-guidelines.git -f
      env:
        REPO_KEY: ${{ secrets.PUSH_PAT }}
        USERNAME: github-actions
