name: html_conversion

on:
  push:
    branches:
    - master
    - gh-pages
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: pocistio   # TODO: update to cluster name
  GKE_ZONE: europe-north1-b   # TODO: update to cluster zone
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor -D docs --backend=html5 -o index.html -a toc2 ddocs/index.adoc 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor '*.adoc' '*/*.adoc'"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./
    - name : Checkout gh-pages
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'gh-pages'
        persist-credentials: false
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GKE_SA_EMAIL }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run:
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run:
        gcloud container clusters get-credentials pocistio --zone europe-north1-b
    - run:
        docker build -t html-server-image:$GITHUB_SHA .
    - run: 
        docker tag html-server-image:$GITHUB_SHA  gcr.io/keycloak-251014/html-server-image:$GITHUB_SHA
    - run: 
        docker push gcr.io/keycloak-251014/html-server-image:$GITHUB_SHA
            # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/keycloak-251014/html-server-image:TAG=gcr.io/keycloak-251014/html-server-image:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
