name: html_conversion

on:
  push:
    branches:
    - master
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: pocistio   # TODO: update to cluster name
  GKE_ZONE: europe-north1-b   # TODO: update to cluster zone
jobs:
  adoc_build:
    runs-on: ubuntu-18.04
    name: asciidoctor -D docs --backend=html5 -o index.html -a toc2 ddocs/index.adoc 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: adocbuild
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor '*.adoc' '*/*.adoc'"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./
    - name : Checkout gh-pages
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'gh-pages'
        persist-credentials: false
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GKE_SA_EMAIL }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run:
       gcloud --quiet auth configure-docker
       gcloud container clusters get-credentials "pocistio" --zone "europe-north1-b"
       docker build -t html-server-image:v1 .
       docker tag html-server-image:v1  gcr.io/keycloak-251014/html-server-image:v1 
       docker push gcr.io/keycloak-251014/html-server-image:v1
